---
title: "EC 710 - Microeconometrics - Syllabus"
author: "Professor: Dr. Bekah Selby"
date: "Term: Summer 2019"
output: html_document 
---

# Contact Information 

- Dr. Bekah Selby
- Office: SH 243
- Office #: 620-341-5645
- Email: [rselby@emporia.edu](mailto:rselby@emporia.edu)
- Office Hours: On Zoom, Fridays @ 3pm 

# Description
This course presents the theory and tools that applied economists use to answer complex questions in microeconomics. This is one of two econometrics courses that satisfy the requirements for the MS Informatics - Quantitative Economics Concentration. This course is held 100\% online with the following structure: 

- **Monday-Thursday**: Self-paced, module-based learning. You will complete modules by submitting assignments. Online XA section students must complete at least two (2) discussion board assignments weekly. This will count for the participation part of the grade. 
- **Friday**: A 1-hour live webinar with Professor Selby. Attendance is **required** for individuals enrolled in the on-campus section (A), which will count for the participation part of the grade. This time may be used for elaboration, tutoring, questions, and discussion. 


The focus in this class will be to prepare students to examine microeconomic data, formulate models, and provide analysis of real-world phenomena.

# Prerequisites
A background in economics, statistics, and calculus is expected. 

# Textbooks:
## Graduate Textbooks

The (**Required**) textbook for this course will be:

- "CAUSAL INFERENCE:THE MIXTAPE (V. 1. 7 )" by Scott Cunningham [Link](http://scunning.com/cunningham_mixtape.pdf)
- "Introduction to Econometrics with R" by Hank, Arnold, Gerber, and Schmelzer [Link](https://www.econometrics-with-r.org/index.html) 
- "Mostly Harmless Econometrics"" by Joshua D. Angrist and J{\"o}rn-Steffen Pischke
	ISBN 978-0691120355
- "R Markdown: The Definitive Guide" Yihui Xie, J. J. Allaire, Garrett Grolemund, [Link](https://bookdown.org/yihui/rmarkdown/)

Other recommended supplements: 

- "Mastering 'Metrics" by Joshua D. Angrist and J{\"o}rn-Steffen Pischke
	ISBN 978-0691152844
- "A Guide to Econometrics" by Peter Kennedy ISBN  978-1405182577

# Technology

- R [(Download)](https://www.r-project.org/)
- R-Studio [(Download)](https://www.rstudio.com/products/rstudio/download/)

# Assessment
Your grade in this course will be determined by achievement in the following categories:

1. Reading Homework (20%)
2. Other Homework (40%)
3. Discussion Board Posts (10%)
3. Replication Projects (30%)


# Grade Criteria

|Letter Grade| Overall Grade| 
|------------|--------------|
|A | 89.50-100% |
|B | 79.50-89.49% |
|C | 69.50-79.49% |
|D | 59.50-69.49% |
|F | 0-59.49% |



# Policy on Late Work
I do not accept late work in this class except under the most extraordinary of circumstances. If you know you will be gone for an assignment or class, please make arrangements to have the work done prior to your absence. I will happily accept early submissions on any due work. 


# Attendance
Attendance is measured in participation during discussions, contact with professor, and interactions with peers. As with most mathematically intensive courses, it is vital for success. You are responsible for obtaining all material in lectures, discussions, and assignments.  You are required to turn in all written work on time. Missing an assignment, activity, or a paper will lower your grade.

# Student Learning Outcomes
Upon completion of this course, students will be able to do the following: 
1. pply the theory behind linear regression analysis, including interpretation of estimated coefficients and goodness of fit.
2.  Develop models appropriate for data and questions.
3.  Illustrate results from panel-data models in a professional and clear way.
4.  Utilize data-analysis software to perform summary analysis and linear regression analysis.
5. Demonstrate mastery of econometric analysis in an academic research replications.
	
# Academic Dishonesty
Academic dishonesty includes, but is not limited to, acts of cheating and plagiarism. Such acts will not be tolerated in this course and will be reported. Consequences for academic dishonesty include an automatic fail (F) in the course. 

# Student Accommodations Statement
Emporia State University will make reasonable accommodations for persons with documented disabilities. Students need to contact the Director of Student Accessibility and Support Services, Stephanie Adams, Plumb Hall 106, and the professor as early in the semester as possible to ensure that classroom and academic accommodations are implemented in a timely fashion. All communication between students, Student Accessibility and Support Services, and the professor will be strictly confidential.

# Diversity Statement 
Emporia State University supports an inclusive learning environment where diversity and individual differences are understood, respected, appreciated, and recognized as a source of strength. We expect that students and faculty at Emporia State will respect differences and demonstrate diligence in understanding how other people's perspectives, behaviors, and world-views may be different from their own.

If there are aspects of the design, instruction, and/or your experiences within this course that result in barriers to your inclusion or accurate assessment of achievement, please notify the unit head (Department Chair or equivalent) as soon as possible, and/or contact the office of the Assistant Dean of Students for Diversity, Equity & Inclusion.
